server:
  port: 5000

spring:
  application:
    name: nocas-blog-provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8090 #Nacos服务注册中心地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1111111111